// auto-generated by sqlc - do not edit
using System;
using System.Collections.Generic;
using System.Linq;

namespace Persistence;
public readonly record struct Product(Guid Id, string Name, string? Brand, bool IsDeleted, DateTime CreatedUtc, DateTime LastUpdatedUtc);