// auto-generated by sqlc - do not edit
using System;
using System.Collections.Generic;
using System.Linq;

namespace Persistence;
public readonly record struct CanonicalProduct(Guid CanonicalProductId, string Barcode, string Brand, string Name, double SizeValue, string SizeUnit, bool IsDeleted, DateTime CreatedUtc, DateTime LastUpdatedUtc);
public readonly record struct StoreProduct(Guid StoreProductId, string StoreName, string Barcode, Guid? CanonicalProductId, string Name, string? Brand, string ImageUrl, string? UnitAndSize, decimal MaxQuantity, bool IsDeleted, DateTime CreatedUtc, DateTime LastUpdatedUtc);
public readonly record struct CanonicalStoreProduct(Guid CanonicalProductId, Guid StoreProductId);