// auto-generated by sqlc - do not edit
using NpgsqlTypes;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Persistence;
public readonly record struct Product(Guid Id, string Sku, string Name, string? Brand, short StoreType, string? ImageUrl, decimal MaxQuantity, bool IsDeleted, DateTime CreatedUtc, DateTime LastUpdatedUtc, NpgsqlTsVector? SearchVector);
public readonly record struct ProductPrice(Guid ProductId, string ProductSku, short StoreType, int RegionId, decimal OriginalPrice, decimal? SalePrice, decimal? MultiBuyPrice, DateTime CreatedUtc, DateTime LastUpdatedUtc);