// auto-generated by sqlc - do not edit
// ReSharper disable UseObjectOrCollectionInitializer
// ReSharper disable UseAwaitUsing
// ReSharper disable ConvertToUsingDeclaration
// ReSharper disable NotAccessedPositionalProperty.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
using Npgsql;
using NpgsqlTypes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace Persistence;
public class QueriesSql
{
    public QueriesSql()
    {
    }

    public QueriesSql(string connectionString) : this()
    {
        this.ConnectionString = connectionString;
    }

    private QueriesSql(NpgsqlTransaction transaction) : this()
    {
        this.Transaction = transaction;
    }

    public static QueriesSql WithTransaction(NpgsqlTransaction transaction)
    {
        return new QueriesSql(transaction);
    }

    private NpgsqlTransaction? Transaction { get; }
    private string? ConnectionString { get; }

    private const string CreateProductSql = "insert into Product (name, brand, sku, store_type, image_url, max_quantity) values (@name, @brand, @sku, @store_type, @image_url, @max_quanitity) returning product.id, product.sku, product.name, product.brand, product.store_type, product.image_url, product.max_quantity, product.is_deleted, product.created_utc, product.last_updated_utc, product.search_vector";
    public readonly record struct CreateProductRow(Product? Product);
    public readonly record struct CreateProductArgs(string Name, string? Brand, string Sku, short StoreType, string? ImageUrl, decimal MaxQuanitity);
    public async Task<CreateProductRow?> CreateProduct(CreateProductArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(CreateProductSql))
                {
                    command.Parameters.AddWithValue("@name", args.Name);
                    command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@sku", args.Sku);
                    command.Parameters.AddWithValue("@store_type", args.StoreType);
                    command.Parameters.AddWithValue("@image_url", args.ImageUrl ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@max_quanitity", args.MaxQuanitity);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (await reader.ReadAsync())
                        {
                            return new CreateProductRow
                            {
                                Product = new Product
                                {
                                    Id = reader.GetFieldValue<Guid>(0),
                                    Sku = reader.GetString(1),
                                    Name = reader.GetString(2),
                                    Brand = reader.IsDBNull(3) ? null : reader.GetString(3),
                                    StoreType = reader.GetInt16(4),
                                    ImageUrl = reader.IsDBNull(5) ? null : reader.GetString(5),
                                    MaxQuantity = reader.GetDecimal(6),
                                    IsDeleted = reader.GetBoolean(7),
                                    CreatedUtc = reader.GetDateTime(8),
                                    LastUpdatedUtc = reader.GetDateTime(9),
                                    SearchVector = reader.IsDBNull(10) ? null : reader.GetFieldValue<NpgsqlTsVector>(10)
                                }
                            };
                        }
                    }
                }
            }

            return null;
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = CreateProductSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@name", args.Name);
            command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@sku", args.Sku);
            command.Parameters.AddWithValue("@store_type", args.StoreType);
            command.Parameters.AddWithValue("@image_url", args.ImageUrl ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@max_quanitity", args.MaxQuanitity);
            using (var reader = await command.ExecuteReaderAsync())
            {
                if (await reader.ReadAsync())
                {
                    return new CreateProductRow
                    {
                        Product = new Product
                        {
                            Id = reader.GetFieldValue<Guid>(0),
                            Sku = reader.GetString(1),
                            Name = reader.GetString(2),
                            Brand = reader.IsDBNull(3) ? null : reader.GetString(3),
                            StoreType = reader.GetInt16(4),
                            ImageUrl = reader.IsDBNull(5) ? null : reader.GetString(5),
                            MaxQuantity = reader.GetDecimal(6),
                            IsDeleted = reader.GetBoolean(7),
                            CreatedUtc = reader.GetDateTime(8),
                            LastUpdatedUtc = reader.GetDateTime(9),
                            SearchVector = reader.IsDBNull(10) ? null : reader.GetFieldValue<NpgsqlTsVector>(10)
                        }
                    };
                }
            }
        }

        return null;
    }

    private const string CreateProductsSql = "COPY product (name, brand, sku, store_type, image_url, max_quantity) FROM STDIN (FORMAT BINARY)";
    public readonly record struct CreateProductsArgs(string Name, string? Brand, string Sku, short StoreType, string? ImageUrl, decimal MaxQuantity);
    public async Task CreateProducts(List<CreateProductsArgs> args)
    {
        using (var connection = new NpgsqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var writer = await connection.BeginBinaryImportAsync(CreateProductsSql))
            {
                foreach (var row in args)
                {
                    await writer.StartRowAsync();
                    await writer.WriteAsync(row.Name);
                    await writer.WriteAsync(row.Brand ?? (object)DBNull.Value);
                    await writer.WriteAsync(row.Sku);
                    await writer.WriteAsync(row.StoreType);
                    await writer.WriteAsync(row.ImageUrl ?? (object)DBNull.Value);
                    await writer.WriteAsync(row.MaxQuantity);
                }

                await writer.CompleteAsync();
            }

            await connection.CloseAsync();
        }
    }

    private const string GetWoolworthsProductsSql = "select id, sku, name, brand, store_type, image_url, max_quantity, is_deleted, created_utc, last_updated_utc, search_vector from product where sku = any(@skus::varchar(255)[]) and store_type = 0 and is_deleted = false";
    public readonly record struct GetWoolworthsProductsRow(Guid Id, string Sku, string Name, string? Brand, short StoreType, string? ImageUrl, decimal MaxQuantity, bool IsDeleted, DateTime CreatedUtc, DateTime LastUpdatedUtc, NpgsqlTsVector? SearchVector);
    public readonly record struct GetWoolworthsProductsArgs(string[] Skus);
    public async Task<List<GetWoolworthsProductsRow>> GetWoolworthsProducts(GetWoolworthsProductsArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(GetWoolworthsProductsSql))
                {
                    command.Parameters.AddWithValue("@skus", args.Skus);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        var result = new List<GetWoolworthsProductsRow>();
                        while (await reader.ReadAsync())
                            result.Add(new GetWoolworthsProductsRow { Id = reader.GetFieldValue<Guid>(0), Sku = reader.GetString(1), Name = reader.GetString(2), Brand = reader.IsDBNull(3) ? null : reader.GetString(3), StoreType = reader.GetInt16(4), ImageUrl = reader.IsDBNull(5) ? null : reader.GetString(5), MaxQuantity = reader.GetDecimal(6), IsDeleted = reader.GetBoolean(7), CreatedUtc = reader.GetDateTime(8), LastUpdatedUtc = reader.GetDateTime(9), SearchVector = reader.IsDBNull(10) ? null : reader.GetFieldValue<NpgsqlTsVector>(10) });
                        return result;
                    }
                }
            }
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = GetWoolworthsProductsSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@skus", args.Skus);
            using (var reader = await command.ExecuteReaderAsync())
            {
                var result = new List<GetWoolworthsProductsRow>();
                while (await reader.ReadAsync())
                    result.Add(new GetWoolworthsProductsRow { Id = reader.GetFieldValue<Guid>(0), Sku = reader.GetString(1), Name = reader.GetString(2), Brand = reader.IsDBNull(3) ? null : reader.GetString(3), StoreType = reader.GetInt16(4), ImageUrl = reader.IsDBNull(5) ? null : reader.GetString(5), MaxQuantity = reader.GetDecimal(6), IsDeleted = reader.GetBoolean(7), CreatedUtc = reader.GetDateTime(8), LastUpdatedUtc = reader.GetDateTime(9), SearchVector = reader.IsDBNull(10) ? null : reader.GetFieldValue<NpgsqlTsVector>(10) });
                return result;
            }
        }
    }

    private const string UpdateProductSql = "update product set name = @name, brand = @brand, image_url = @image_url, max_quantity = @max_quantity, last_updated_utc = now() where sku = @sku and store_type = @store_type";
    public readonly record struct UpdateProductArgs(string Name, string? Brand, string? ImageUrl, decimal MaxQuantity, string Sku, short StoreType);
    public async Task UpdateProduct(UpdateProductArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(UpdateProductSql))
                {
                    command.Parameters.AddWithValue("@name", args.Name);
                    command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@image_url", args.ImageUrl ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@max_quantity", args.MaxQuantity);
                    command.Parameters.AddWithValue("@sku", args.Sku);
                    command.Parameters.AddWithValue("@store_type", args.StoreType);
                    await command.ExecuteNonQueryAsync();
                }
            }

            return;
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = UpdateProductSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@name", args.Name);
            command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@image_url", args.ImageUrl ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@max_quantity", args.MaxQuantity);
            command.Parameters.AddWithValue("@sku", args.Sku);
            command.Parameters.AddWithValue("@store_type", args.StoreType);
            await command.ExecuteNonQueryAsync();
        }
    }

    private const string CreateProductPriceSql = "insert into Product_Price (product_id, product_sku, store_type, region_id, original_price, sale_price, multi_buy_price) values (@product_id, @product_sku, @store_type, @region_id, @original_price, @sale_price, @multi_buy_price)";
    public readonly record struct CreateProductPriceArgs(Guid ProductId, string ProductSku, short StoreType, int RegionId, decimal OriginalPrice, decimal? SalePrice, decimal? MultiBuyPrice);
    public async Task CreateProductPrice(CreateProductPriceArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(CreateProductPriceSql))
                {
                    command.Parameters.AddWithValue("@product_id", args.ProductId);
                    command.Parameters.AddWithValue("@product_sku", args.ProductSku);
                    command.Parameters.AddWithValue("@store_type", args.StoreType);
                    command.Parameters.AddWithValue("@region_id", args.RegionId);
                    command.Parameters.AddWithValue("@original_price", args.OriginalPrice);
                    command.Parameters.AddWithValue("@sale_price", args.SalePrice ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@multi_buy_price", args.MultiBuyPrice ?? (object)DBNull.Value);
                    await command.ExecuteNonQueryAsync();
                }
            }

            return;
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = CreateProductPriceSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@product_id", args.ProductId);
            command.Parameters.AddWithValue("@product_sku", args.ProductSku);
            command.Parameters.AddWithValue("@store_type", args.StoreType);
            command.Parameters.AddWithValue("@region_id", args.RegionId);
            command.Parameters.AddWithValue("@original_price", args.OriginalPrice);
            command.Parameters.AddWithValue("@sale_price", args.SalePrice ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@multi_buy_price", args.MultiBuyPrice ?? (object)DBNull.Value);
            await command.ExecuteNonQueryAsync();
        }
    }

    private const string SearchProductsSql = "SELECT product.id, product.sku, product.name, product.brand, product.store_type, product.image_url, product.max_quantity, product.is_deleted, product.created_utc, product.last_updated_utc, product.search_vector FROM Product WHERE is_deleted = false AND search_vector @@ plainto_tsquery('english', @query) ORDER BY ts_rank_cd(search_vector, plainto_tsquery('english', @query)) DESC, id asc LIMIT @limit::int OFFSET @offset::int";
    public readonly record struct SearchProductsRow(Product? Product);
    public readonly record struct SearchProductsArgs(string Query, int? Offset, int? Limit);
    public async Task<List<SearchProductsRow>> SearchProducts(SearchProductsArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(SearchProductsSql))
                {
                    command.Parameters.AddWithValue("@query", args.Query);
                    command.Parameters.AddWithValue("@offset", args.Offset ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@limit", args.Limit ?? (object)DBNull.Value);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        var result = new List<SearchProductsRow>();
                        while (await reader.ReadAsync())
                            result.Add(new SearchProductsRow { Product = new Product { Id = reader.GetFieldValue<Guid>(0), Sku = reader.GetString(1), Name = reader.GetString(2), Brand = reader.IsDBNull(3) ? null : reader.GetString(3), StoreType = reader.GetInt16(4), ImageUrl = reader.IsDBNull(5) ? null : reader.GetString(5), MaxQuantity = reader.GetDecimal(6), IsDeleted = reader.GetBoolean(7), CreatedUtc = reader.GetDateTime(8), LastUpdatedUtc = reader.GetDateTime(9), SearchVector = reader.IsDBNull(10) ? null : reader.GetFieldValue<NpgsqlTsVector>(10) } });
                        return result;
                    }
                }
            }
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = SearchProductsSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@query", args.Query);
            command.Parameters.AddWithValue("@offset", args.Offset ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@limit", args.Limit ?? (object)DBNull.Value);
            using (var reader = await command.ExecuteReaderAsync())
            {
                var result = new List<SearchProductsRow>();
                while (await reader.ReadAsync())
                    result.Add(new SearchProductsRow { Product = new Product { Id = reader.GetFieldValue<Guid>(0), Sku = reader.GetString(1), Name = reader.GetString(2), Brand = reader.IsDBNull(3) ? null : reader.GetString(3), StoreType = reader.GetInt16(4), ImageUrl = reader.IsDBNull(5) ? null : reader.GetString(5), MaxQuantity = reader.GetDecimal(6), IsDeleted = reader.GetBoolean(7), CreatedUtc = reader.GetDateTime(8), LastUpdatedUtc = reader.GetDateTime(9), SearchVector = reader.IsDBNull(10) ? null : reader.GetFieldValue<NpgsqlTsVector>(10) } });
                return result;
            }
        }
    }
}