// auto-generated by sqlc - do not edit
// ReSharper disable UseObjectOrCollectionInitializer
// ReSharper disable UseAwaitUsing
// ReSharper disable ConvertToUsingDeclaration
// ReSharper disable NotAccessedPositionalProperty.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace Persistence;
public class QueriesSql
{
    public QueriesSql()
    {
    }

    public QueriesSql(string connectionString) : this()
    {
        this.ConnectionString = connectionString;
    }

    private QueriesSql(NpgsqlTransaction transaction) : this()
    {
        this.Transaction = transaction;
    }

    public static QueriesSql WithTransaction(NpgsqlTransaction transaction)
    {
        return new QueriesSql(transaction);
    }

    private NpgsqlTransaction? Transaction { get; }
    private string? ConnectionString { get; }

    private const string CreateProductsSql = "COPY store_product (store_name, barcode, name, brand, image_url, max_quantity, unit_and_size) FROM STDIN (FORMAT BINARY)";
    public readonly record struct CreateProductsArgs(string StoreName, string Barcode, string Name, string? Brand, string ImageUrl, decimal MaxQuantity, string? UnitAndSize);
    public async Task CreateProducts(List<CreateProductsArgs> args)
    {
        using (var connection = new NpgsqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var writer = await connection.BeginBinaryImportAsync(CreateProductsSql))
            {
                foreach (var row in args)
                {
                    await writer.StartRowAsync();
                    await writer.WriteAsync(row.StoreName);
                    await writer.WriteAsync(row.Barcode);
                    await writer.WriteAsync(row.Name);
                    await writer.WriteAsync(row.Brand ?? (object)DBNull.Value);
                    await writer.WriteAsync(row.ImageUrl);
                    await writer.WriteAsync(row.MaxQuantity);
                    await writer.WriteAsync(row.UnitAndSize ?? (object)DBNull.Value);
                }

                await writer.CompleteAsync();
            }

            await connection.CloseAsync();
        }
    }

    private const string SearchProductsSql = "SELECT canonical_product.canonical_product_id, canonical_product.barcode, canonical_product.brand, canonical_product.name, canonical_product.size_value, canonical_product.size_unit, canonical_product.is_deleted, canonical_product.created_utc, canonical_product.last_updated_utc FROM canonical_product WHERE is_deleted = false AND search_vector @@ plainto_tsquery('english', @query) ORDER BY ts_rank_cd(search_vector, plainto_tsquery('english', @query)) DESC, canonical_product_id asc LIMIT @limit::int OFFSET @offset::int";
    public readonly record struct SearchProductsRow(CanonicalProduct? CanonicalProduct);
    public readonly record struct SearchProductsArgs(string Query, int? Offset, int? Limit);
    public async Task<List<SearchProductsRow>> SearchProducts(SearchProductsArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(SearchProductsSql))
                {
                    command.Parameters.AddWithValue("@query", args.Query);
                    command.Parameters.AddWithValue("@offset", args.Offset ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@limit", args.Limit ?? (object)DBNull.Value);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        var result = new List<SearchProductsRow>();
                        while (await reader.ReadAsync())
                            result.Add(new SearchProductsRow { CanonicalProduct = new CanonicalProduct { CanonicalProductId = reader.GetFieldValue<Guid>(0), Barcode = reader.GetString(1), Brand = reader.GetString(2), Name = reader.GetString(3), SizeValue = reader.GetDouble(4), SizeUnit = reader.GetString(5), IsDeleted = reader.GetBoolean(6), CreatedUtc = reader.GetDateTime(7), LastUpdatedUtc = reader.GetDateTime(8) } });
                        return result;
                    }
                }
            }
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = SearchProductsSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@query", args.Query);
            command.Parameters.AddWithValue("@offset", args.Offset ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@limit", args.Limit ?? (object)DBNull.Value);
            using (var reader = await command.ExecuteReaderAsync())
            {
                var result = new List<SearchProductsRow>();
                while (await reader.ReadAsync())
                    result.Add(new SearchProductsRow { CanonicalProduct = new CanonicalProduct { CanonicalProductId = reader.GetFieldValue<Guid>(0), Barcode = reader.GetString(1), Brand = reader.GetString(2), Name = reader.GetString(3), SizeValue = reader.GetDouble(4), SizeUnit = reader.GetString(5), IsDeleted = reader.GetBoolean(6), CreatedUtc = reader.GetDateTime(7), LastUpdatedUtc = reader.GetDateTime(8) } });
                return result;
            }
        }
    }

    private const string GetStoreProductsSql = "select store_product.store_product_id, store_product.store_name, store_product.barcode, store_product.canonical_product_id, store_product.name, store_product.brand, store_product.image_url, store_product.unit_and_size, store_product.max_quantity, store_product.is_deleted, store_product.created_utc, store_product.last_updated_utc from store_product where barcode = any(@skus::varchar(255)[]) and store_name = @store_name and is_deleted = false";
    public readonly record struct GetStoreProductsRow(StoreProduct? StoreProduct);
    public readonly record struct GetStoreProductsArgs(string[] Skus, string StoreName);
    public async Task<List<GetStoreProductsRow>> GetStoreProducts(GetStoreProductsArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(GetStoreProductsSql))
                {
                    command.Parameters.AddWithValue("@skus", args.Skus);
                    command.Parameters.AddWithValue("@store_name", args.StoreName);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        var result = new List<GetStoreProductsRow>();
                        while (await reader.ReadAsync())
                            result.Add(new GetStoreProductsRow { StoreProduct = new StoreProduct { StoreProductId = reader.GetFieldValue<Guid>(0), StoreName = reader.GetString(1), Barcode = reader.GetString(2), CanonicalProductId = reader.IsDBNull(3) ? null : reader.GetFieldValue<Guid>(3), Name = reader.GetString(4), Brand = reader.IsDBNull(5) ? null : reader.GetString(5), ImageUrl = reader.GetString(6), UnitAndSize = reader.IsDBNull(7) ? null : reader.GetString(7), MaxQuantity = reader.GetDecimal(8), IsDeleted = reader.GetBoolean(9), CreatedUtc = reader.GetDateTime(10), LastUpdatedUtc = reader.GetDateTime(11) } });
                        return result;
                    }
                }
            }
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = GetStoreProductsSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@skus", args.Skus);
            command.Parameters.AddWithValue("@store_name", args.StoreName);
            using (var reader = await command.ExecuteReaderAsync())
            {
                var result = new List<GetStoreProductsRow>();
                while (await reader.ReadAsync())
                    result.Add(new GetStoreProductsRow { StoreProduct = new StoreProduct { StoreProductId = reader.GetFieldValue<Guid>(0), StoreName = reader.GetString(1), Barcode = reader.GetString(2), CanonicalProductId = reader.IsDBNull(3) ? null : reader.GetFieldValue<Guid>(3), Name = reader.GetString(4), Brand = reader.IsDBNull(5) ? null : reader.GetString(5), ImageUrl = reader.GetString(6), UnitAndSize = reader.IsDBNull(7) ? null : reader.GetString(7), MaxQuantity = reader.GetDecimal(8), IsDeleted = reader.GetBoolean(9), CreatedUtc = reader.GetDateTime(10), LastUpdatedUtc = reader.GetDateTime(11) } });
                return result;
            }
        }
    }

    private const string GetStoreProductsByStoreSql = "select store_product.store_product_id, store_product.store_name, store_product.barcode, store_product.canonical_product_id, store_product.name, store_product.brand, store_product.image_url, store_product.unit_and_size, store_product.max_quantity, store_product.is_deleted, store_product.created_utc, store_product.last_updated_utc from store_product where store_name = @store_name and is_deleted = false";
    public readonly record struct GetStoreProductsByStoreRow(StoreProduct? StoreProduct);
    public readonly record struct GetStoreProductsByStoreArgs(string StoreName);
    public async Task<List<GetStoreProductsByStoreRow>> GetStoreProductsByStore(GetStoreProductsByStoreArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(GetStoreProductsByStoreSql))
                {
                    command.Parameters.AddWithValue("@store_name", args.StoreName);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        var result = new List<GetStoreProductsByStoreRow>();
                        while (await reader.ReadAsync())
                            result.Add(new GetStoreProductsByStoreRow { StoreProduct = new StoreProduct { StoreProductId = reader.GetFieldValue<Guid>(0), StoreName = reader.GetString(1), Barcode = reader.GetString(2), CanonicalProductId = reader.IsDBNull(3) ? null : reader.GetFieldValue<Guid>(3), Name = reader.GetString(4), Brand = reader.IsDBNull(5) ? null : reader.GetString(5), ImageUrl = reader.GetString(6), UnitAndSize = reader.IsDBNull(7) ? null : reader.GetString(7), MaxQuantity = reader.GetDecimal(8), IsDeleted = reader.GetBoolean(9), CreatedUtc = reader.GetDateTime(10), LastUpdatedUtc = reader.GetDateTime(11) } });
                        return result;
                    }
                }
            }
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = GetStoreProductsByStoreSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@store_name", args.StoreName);
            using (var reader = await command.ExecuteReaderAsync())
            {
                var result = new List<GetStoreProductsByStoreRow>();
                while (await reader.ReadAsync())
                    result.Add(new GetStoreProductsByStoreRow { StoreProduct = new StoreProduct { StoreProductId = reader.GetFieldValue<Guid>(0), StoreName = reader.GetString(1), Barcode = reader.GetString(2), CanonicalProductId = reader.IsDBNull(3) ? null : reader.GetFieldValue<Guid>(3), Name = reader.GetString(4), Brand = reader.IsDBNull(5) ? null : reader.GetString(5), ImageUrl = reader.GetString(6), UnitAndSize = reader.IsDBNull(7) ? null : reader.GetString(7), MaxQuantity = reader.GetDecimal(8), IsDeleted = reader.GetBoolean(9), CreatedUtc = reader.GetDateTime(10), LastUpdatedUtc = reader.GetDateTime(11) } });
                return result;
            }
        }
    }

    private const string UpdateStoreProductSql = "update store_product set name = @name, brand = @brand, image_url = @image_url, max_quantity = @max_quantity, last_updated_utc = now() where barcode = @barcode and store_name = @store_name";
    public readonly record struct UpdateStoreProductArgs(string Name, string? Brand, string ImageUrl, decimal MaxQuantity, string Barcode, string StoreName);
    public async Task UpdateStoreProduct(UpdateStoreProductArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(UpdateStoreProductSql))
                {
                    command.Parameters.AddWithValue("@name", args.Name);
                    command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@image_url", args.ImageUrl);
                    command.Parameters.AddWithValue("@max_quantity", args.MaxQuantity);
                    command.Parameters.AddWithValue("@barcode", args.Barcode);
                    command.Parameters.AddWithValue("@store_name", args.StoreName);
                    await command.ExecuteNonQueryAsync();
                }
            }

            return;
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = UpdateStoreProductSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@name", args.Name);
            command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@image_url", args.ImageUrl);
            command.Parameters.AddWithValue("@max_quantity", args.MaxQuantity);
            command.Parameters.AddWithValue("@barcode", args.Barcode);
            command.Parameters.AddWithValue("@store_name", args.StoreName);
            await command.ExecuteNonQueryAsync();
        }
    }
}