// auto-generated by sqlc - do not edit
// ReSharper disable UseObjectOrCollectionInitializer
// ReSharper disable UseAwaitUsing
// ReSharper disable ConvertToUsingDeclaration
// ReSharper disable NotAccessedPositionalProperty.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace Persistence;
public class QueriesSql
{
    public QueriesSql()
    {
    }

    public QueriesSql(string connectionString) : this()
    {
        this.ConnectionString = connectionString;
    }

    private QueriesSql(NpgsqlTransaction transaction) : this()
    {
        this.Transaction = transaction;
    }

    public static QueriesSql WithTransaction(NpgsqlTransaction transaction)
    {
        return new QueriesSql(transaction);
    }

    private NpgsqlTransaction? Transaction { get; }
    private string? ConnectionString { get; }

    private const string CreateProductSql = "insert into Product (name, brand) values (@name, @brand) returning product.id, product.name, product.brand, product.is_deleted, product.created_utc, product.last_updated_utc";
    public readonly record struct CreateProductRow(Product? Product);
    public readonly record struct CreateProductArgs(string Name, string? Brand);
    public async Task<CreateProductRow?> CreateProduct(CreateProductArgs args)
    {
        if (this.Transaction == null)
        {
            using (var connection = NpgsqlDataSource.Create(ConnectionString!))
            {
                using (var command = connection.CreateCommand(CreateProductSql))
                {
                    command.Parameters.AddWithValue("@name", args.Name);
                    command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (await reader.ReadAsync())
                        {
                            return new CreateProductRow
                            {
                                Product = new Product
                                {
                                    Id = reader.GetFieldValue<Guid>(0),
                                    Name = reader.GetString(1),
                                    Brand = reader.IsDBNull(2) ? null : reader.GetString(2),
                                    IsDeleted = reader.GetBoolean(3),
                                    CreatedUtc = reader.GetDateTime(4),
                                    LastUpdatedUtc = reader.GetDateTime(5)
                                }
                            };
                        }
                    }
                }
            }

            return null;
        }

        if (this.Transaction?.Connection == null || this.Transaction?.Connection.State != System.Data.ConnectionState.Open)
            throw new InvalidOperationException("Transaction is provided, but its connection is null.");
        using (var command = this.Transaction.Connection.CreateCommand())
        {
            command.CommandText = CreateProductSql;
            command.Transaction = this.Transaction;
            command.Parameters.AddWithValue("@name", args.Name);
            command.Parameters.AddWithValue("@brand", args.Brand ?? (object)DBNull.Value);
            using (var reader = await command.ExecuteReaderAsync())
            {
                if (await reader.ReadAsync())
                {
                    return new CreateProductRow
                    {
                        Product = new Product
                        {
                            Id = reader.GetFieldValue<Guid>(0),
                            Name = reader.GetString(1),
                            Brand = reader.IsDBNull(2) ? null : reader.GetString(2),
                            IsDeleted = reader.GetBoolean(3),
                            CreatedUtc = reader.GetDateTime(4),
                            LastUpdatedUtc = reader.GetDateTime(5)
                        }
                    };
                }
            }
        }

        return null;
    }

    private const string CreateProductsSql = "COPY product (name, brand) FROM STDIN (FORMAT BINARY)";
    public readonly record struct CreateProductsArgs(string Name, string? Brand);
    public async Task CreateProducts(List<CreateProductsArgs> args)
    {
        using (var connection = new NpgsqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var writer = await connection.BeginBinaryImportAsync(CreateProductsSql))
            {
                foreach (var row in args)
                {
                    await writer.StartRowAsync();
                    await writer.WriteAsync(row.Name);
                    await writer.WriteAsync(row.Brand ?? (object)DBNull.Value);
                }

                await writer.CompleteAsync();
            }

            await connection.CloseAsync();
        }
    }
}